#!/bin/bash

BINTRAY_JSON="$(dirname $(readlink -f $0))/../build/bintray.json"
GIT_REVISION="$(git describe --tags --always --dirty)"

BINTRAY_SUBJECT="${BINTRAY_SUBJECT:-retroheim-base}"
BINTRAY_REPO="${BINTRAY_REPO:-BigBrother}"
BINTRAY_PACKAGE="${BINTRAY_PACKAGE:-BigBrother}"
BINTRAY_FLAVOR=""

if [[ $TRAVIS_BRANCH != master ]]; then
	BINTRAY_FLAVOR="-${TRAVIS_BRANCH}"
fi

tee "${BINTRAY_JSON}" <<EOF
{
  "package": {
    "name": "${BINTRAY_PACKAGE}${BINTRAY_FLAVOR}",
    "repo": "${BINTRAY_REPO}",
    "subject": "${BINTRAY_SUBJECT}",
  },

  "version": {
    "name": "${GIT_REVISION}"
  },

  "files":
    [
      {"includePattern": "build/BigBrother.phar", "uploadPattern": "${TRAVIS_BRANCH}/BigBrother-${GIT_REVISION}.phar"}
    ],
  "publish": true
}
EOF
